---

 - hosts: Alpine
   become: true
   vars:
    ansible_become_method: doas
    ansible_python_interpreter: auto_silent
   tasks:

   - name: Add repository file
     copy:
         src: repositories
         dest: /etc/apk/repositories
         owner: root
         group: root
         mode: 0644

   - name: Install updates
     community.general.apk:
         update_cache: true
         upgrade: true

   - name: Install basic packages
     community.general.apk:
         update_cache: true
         name: doas,mc,htop,tmux
         state: latest

   - name: Create users mejsnar
     user:
         name: mejsnar
         update_password: on_create
         password: '*'
         groups: wheel
         shell: /bin/ash

   - name: Create users ansible
     user:
         name: ansible
         update_password: on_create
         password: '*'
         groups: wheel
         shell: /bin/ash

   - name: Add SSH keys for user mejsnar
     authorized_key:
         user: mejsnar
         key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAchi11PTcAr+5VV1ZOhvaP9eSz1YYYD8bjYGZ9d4kW+ mejsnar"
    
   - name: Add SSH keys for user ansible  
     authorized_key:
         user: ansible
         key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICrTU3a7BdGwUfBFmHi4eOBRUTOVju0sRQTUvHQrLn2O ansible"

   - name: Add doas.conf file
     copy:
         src: doas.conf
         dest: /etc/doas.conf
         owner: root
         group: root
         mode: 0640

   - name: Add sshd_config file
     copy:
         src: sshd_config
         dest: /etc/ssh/sshd_config
         owner: root
         group: root
         mode: 0644