---

 - hosts: all
   become: true
   tasks:
   
   - name: Install updates for Ubuntu and Debian
     apt:
         upgrade: dist
         update_cache: true
     when: ansible_distribution in ["Ubuntu", "Debian"]
   
   - name: Install updates for RHEL based distributions
     dnf:
         name: "*"
         state: latest
         update_cache: true
     when: ansible_distribution in ["Rocky", "CentOS"]

   - name: Install updates for Alpine linux
     community.general.apk:
         update_cache: true
         name: doas
         state: latest
     when: ansible_distribution in ["Alpine"]

   - name: Install EPEL repository and other RHEL specific software
     dnf:
         name: 
         - epel-release
         - yum-utils
         - dnf-automatic
         state: latest
     when: ansible_distribution in ["Rocky", "CentOS"]

   - name: Install Ubuntu/Debian specific software
     apt:
         name:
         - unattended-upgrades
         state: latest
     when: ansible_distribution in ["Ubuntu", "Debian"]

   - name: Install doas for Alpine linux
     community.general.apk:
         update_cache: true
         upgrade: true
     when: ansible_distribution in ["Alpine"]

   - name: Install basic packages for all distributions
     package:
         name: 
         - vim
         - mc
         - htop
         - tmux
         state: latest

   - name: Add unattended-upgrades config file
     copy:
         src: 50unattended-upgrades
         dest: /etc/apt/apt.conf.d/50unattended-upgrades
         owner: root
         group: root
         mode: 0644
     when: ansible_distribution in ["Ubuntu", "Debian"]

   - name: Add unattended-upgrades config file
     copy:
         src: 20auto-upgrades
         dest: /etc/apt/apt.conf.d/20auto-upgrades
         owner: root
         group: root
         mode: 0644
     when: ansible_distribution in ["Ubuntu", "Debian"]
   
   - name: Enable a timer unit for dnf-automatic and set automatic restart if required
     systemd:
       name: dnf-automatic-install.timer
       state: started
       enabled: yes
     when: ansible_distribution in ["Rocky", "CentOS"]

   - name: Create restart script (RHEL)
     copy:
         src: restart_required.sh
         dest: /root/restart_required.sh
         owner: root
         group: root
         mode: 0755
     when: ansible_distribution in ["Rocky", "CentOS"]

   - name: Create cron job for restart script (RHEL)
     cron:
         name: "Requiered restart after update"
         user: root
         minute: 0
         hour: 4
         day: "*"
         month: "*"
         weekday: "*"
         job: /bin/bash /root/restart_required.sh
     when: ansible_distribution in ["Rocky", "CentOS"]

   - name: Create users mejsnar in Ubuntu/Debian
     user:
         name: mejsnar
         groups: sudo, adm
         shell: /bin/bash
         append: yes
     when: ansible_distribution in ["Ubuntu", "Debian"]
    
   - name: Create users mejsnar in RHEL Ditributions
     user:
         name: mejsnar
         groups: wheel
         shell: /bin/bash
         append: yes
     when: ansible_distribution in ["Rocky", "CentOS"]

   - name: Create users mejsnar in Alpine linux
     user:
         name: mejsnar
         groups: wheel
         shell: /bin/ash
     when: ansible_distribution in ["Alpine"]
    
   - name: Create users ansible in all RHEL/Debian distros
     user:
         name: ansible
         shell: /bin/bash
     when: ansible_distribution in ["Rocky", "CentOS", "Ubuntu", "Debian"]

   - name: Create users ansible in Alpine linux
     user:
         name: ansible
         groups: wheel
         shell: /bin/ash
     when: ansible_distribution in ["Alpine"]

   - name: Add SSH keys for user mejsnar
     authorized_key:
         user: mejsnar
         key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAchi11PTcAr+5VV1ZOhvaP9eSz1YYYD8bjYGZ9d4kW+ mejsnar"
    
   - name: Add SSH keys for user ansible  
     authorized_key:
         user: ansible
         key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICrTU3a7BdGwUfBFmHi4eOBRUTOVju0sRQTUvHQrLn2O ansible"
    
   - name: Add sudoers file for ansible user account (RHEL/Debian distros)
     copy:
         src: sudoer_ansible
         dest: /etc/sudoers.d/ansible
         owner: root
         group: root
         mode: 0440
     when: ansible_distribution in ["Rocky", "CentOS", "Ubuntu", "Debian"]

   - name: Add doas.conf file to Alpine linux
     copy:
         src: doas.conf
         dest: /etc/doas.conf
         owner: root
         group: root
         mode: 0640
     when: ansible_distribution in ["Alpine"]